name: 'Create a Release'
description: 'Create a release for a tag in your repository'
author: 'GitHub'
inputs:
  draft:
    description: '`true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`'
    required: false
    default: false
  prerelease:
    description: '`true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`'
    required: false
    default: false
  commitish:
    description: 'Any branch or commit SHA the Git tag is created from, unused if the Git tag already exists. Default: SHA of current commit'
    required: false
  upm_tag_prefix:
    description: 'Tag prefix of verional tag'
    required: true
    default: ''
  upm_package_path:
    description: 'Path of unity package which should contain a package.json file.'
    required: true
    default: ''
outputs:
  id:
    description: 'The ID of the created Release'
  html_url:
    description: 'The URL users can navigate to in order to view the release'
  upload_url:
    description: 'The URL for uploading assets to the release'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'gray-dark'
